name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JC Action
        id: greet
        uses: /actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: eRmaN
      - name: Log Greeting Tİme
        run: echo "${{ steps.greet.outputs.time }}"